### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by sashokbg** [couchbase/CouchbaseMock#25]
Hello

Great project that might be very useful for integration testing. However without any releases it will be hard to convince my superiors to integrate it in our project.

Are you planning to release it on maven central ?

Thank you 
Alexander KIRILOV

**Comment by manikmagar** [comment]
I agree, looking for using this but it will be difficult to integrate with CI without having release on maven central.

**Comment by csaltos** [comment]
Same here, can this project be published at central ?

**Comment by mnunberg** [comment]
https://search.maven.org/#artifactdetails%7Ccom.couchbase.mock%7CCouchbaseMock%7C1.5.1%7Cjar

**Comment by manikmagar** [comment]
:+1:  Awesome, I was just checking on this one last night. Thank you!

**Comment by sashokbg** [comment]
Thank you guys ! This is how professionals do it :+1:  :)
