### ISSUE TITLE
Properly shade third party dependencies

### ISSUE THREAD

**Issue by snicoll** [couchbase/CouchbaseMock#33]
For some reason that I don't understand, this project repackages gson and a bunch of other libraries.

This prevents `CouchbaseMock` to be integrated in Spring Boot. If you decide to go with a one-jar only solution, please shade those libs so that they end up in a different package.

**Comment by avsej** [comment]
@snicoll you can always run CouchbaseMock in separate JVM, and this will eliminate all packaging issues. And this is how actually we run it.

**Comment by avsej** [comment]
I definitely support this idea. What I mean is that currently for our needs running mock in separate process serves well. And we always open for contributions, so if you have patch which is tested to work in your usecases, I will be glad to review and accept it.

**Comment by daschl** [comment]
it's valid that people use it for testing, we just don't officially support it. I think we should fix these errors as they come up and that people can use it in boot. I just wanted to add the note of caution here thats its different as like the couchbase SDK or our spring data integration.

**Comment by snicoll** [comment]
> it's valid that people use it for testing, we just don't officially support it.

I am confused. What else could you do with a project called `CouchbaseMock` ?

**Comment by daschl** [comment]
sorry @snicoll I meant to say "external users" use it for testing (especially in the boot context), compared to we just use it internally.

**Comment by avsej** [comment]
Also we assume that users have to be familiar with CouchbaseMock internals or with the way how it works. As it is not drop-in replacement of Couchbase Server. For example it does not provide support for recent features like analytics or full-text search, also it does not have full support of N1QL. We might add it later, or can accept user contribution.

As domain and usecase of the problem described in this ticket on the Spring Boot side, is it possible that someone from user of from your team will fix, validate and send us the patch with the fix?

**Comment by avsej** [comment]
> I am now processing that PR to see what I can add to make this feature available outside of Spring Boot in case the reporter wants to do that. I'll decline the PR for the reasons discussed above.

Yes, that would be good. I definitely support you in directing reporters to contribute their fixes into CouchbaseMock first.

> As far as I am concerned, this issue can be closed if you clearly describe the scope of the library (i.e. that it shades dependencies and that it cannot be embedded).

We are not against shades. Right now the only requirements is that final jar should be executable without any extra dependencies in classpath. So shaded libraries is an option.

**Comment by snicoll** [comment]
As far as this issue is concerned, I'd welcome a warning about not embedding couchbase in the project itself in the documentation.

**Comment by avsej** [comment]
@Aloren I would be happy to see and review the patch. But so far we've successfully used the mock in separate process across our projects. I belive relocating deps will not hurt.

**Comment by Aloren** [comment]
@avsej ok. i will create pr. thanks!

**Comment by avsej** [comment]
@Aloren note that we use http://review.couchbase.org/ for code submissions and review, and generally do not merge PRs. If you want your change accepted, you have to register on gerrit, sign [CLA](http://review.couchbase.org/#/settings/new-agreement) and submit your patch there.

**Comment by avsej** [comment]
@Aloren I've left notes in http://review.couchbase.org/c/102748/, please let me know there if you have any questions about it.

**Comment by Aloren** [comment]
ok, i will check that in the evening. thanks for the review

**Comment by avsej** [comment]
Fixed in 99084d4fab780e1abc1ce4cab4940c6824f3d343
