### ISSUE TITLE
Repository out of date

### ISSUE THREAD

**Issue by JonboyM** [couchbase/CouchbaseMock#7]
The repository does not appear to have anything newer that the 0.8 snapshot...

https://files.couchbase.com/maven2/org/couchbase/mock/CouchbaseMock/

Is there a plan to push the latest version of the Couchbase mock to the repository?

**Comment by mnunberg** [comment]
We're currently adding the jar files to a different location. We recommend you build the artifact from source and store it elsewhere as CouchbaseMock is not an official location. The build process should be simple and only requires maven.

Furthermore, behavior and APIs are subject to change.

**Comment by mnunberg** [comment]
https://search.maven.org/#artifactdetails%7Ccom.couchbase.mock%7CCouchbaseMock%7C1.5.1%7Cjar
